import {Sora } from "next/font/google";
import "./globals.css";
import { UserProvider } from "./context/Provider";
import { Toaster } from "react-hot-toast";

const fontSora = Sora({
  variable: "--font-sora",
  weight: [ "400", "200"],
  subsets: ["latin"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${fontSora.variable} antialiased`}
      >
        <UserProvider>
          <Toaster position="top-center"/>
          {children}
          </UserProvider>
      </body>
    </html>
  );
}
